"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class info_t(object):
    __slots__ = ["id", "priority", "user", "enabled"]

    def __init__(self):
        self.id = 0
        self.priority = 0.0
        self.user = 0
        self.enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hfhb", self.id, self.priority, self.user, self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = info_t()
        self.id, self.priority, self.user = struct.unpack(">hfh", buf.read(8))
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if info_t in parents: return 0
        tmphash = (0xefe152b98e5058d0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if info_t._packed_fingerprint is None:
            info_t._packed_fingerprint = struct.pack(">Q", info_t._get_hash_recursive([]))
        return info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

