# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(923, 302)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.fileEdit = QtGui.QLineEdit(self.centralwidget)
        self.fileEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.fileEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fileEdit.setFont(font)
        self.fileEdit.setObjectName(_fromUtf8("fileEdit"))
        self.horizontalLayout_2.addWidget(self.fileEdit)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.openButton = QtGui.QPushButton(self.centralwidget)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout_2.addWidget(self.openButton)
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.testSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.testSpinBox.setMinimumSize(QtCore.QSize(0, 80))
        self.testSpinBox.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.testSpinBox.setFont(font)
        self.testSpinBox.setReadOnly(True)
        self.testSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.testSpinBox.setMaximum(100000000)
        self.testSpinBox.setObjectName(_fromUtf8("testSpinBox"))
        self.verticalLayout_2.addWidget(self.testSpinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(0, 120))
        self.startButton.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 120))
        self.stopButton.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sucessButton = QtGui.QPushButton(self.centralwidget)
        self.sucessButton.setMinimumSize(QtCore.QSize(0, 50))
        self.sucessButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sucessButton.setFont(font)
        self.sucessButton.setObjectName(_fromUtf8("sucessButton"))
        self.verticalLayout.addWidget(self.sucessButton)
        self.failButton = QtGui.QPushButton(self.centralwidget)
        self.failButton.setMinimumSize(QtCore.QSize(0, 50))
        self.failButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.failButton.setFont(font)
        self.failButton.setObjectName(_fromUtf8("failButton"))
        self.verticalLayout.addWidget(self.failButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 17))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startButton, self.openButton)
        MainWindow.setTabOrder(self.openButton, self.closeButton)
        MainWindow.setTabOrder(self.closeButton, self.testSpinBox)
        MainWindow.setTabOrder(self.testSpinBox, self.fileEdit)
        MainWindow.setTabOrder(self.fileEdit, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.sucessButton)
        MainWindow.setTabOrder(self.sucessButton, self.failButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "File Name  ", None))
        self.openButton.setText(_translate("MainWindow", "Select Folder", None))
        self.closeButton.setText(_translate("MainWindow", "Close", None))
        self.closeButton.setShortcut(_translate("MainWindow", "E", None))
        self.label.setText(_translate("MainWindow", "Test Number", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.startButton.setShortcut(_translate("MainWindow", "Q", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.stopButton.setShortcut(_translate("MainWindow", "W", None))
        self.sucessButton.setText(_translate("MainWindow", "Sucess", None))
        self.sucessButton.setShortcut(_translate("MainWindow", "S", None))
        self.failButton.setText(_translate("MainWindow", "Failed", None))
        self.failButton.setShortcut(_translate("MainWindow", "F", None))

