/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace oculuslcm
{
    public sealed class info_t : LCM.LCM.LCMEncodable
    {
        public short id;
        public float confidence;
        public float threshold;
        public short user;
        public bool enabled;
 
        public info_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xdb029d012ed70616L;
 
        static info_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("oculuslcm.info_t"))
                return 0L;
 
            classes.Add("oculuslcm.info_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.id); 
 
            outs.Write(this.confidence); 
 
            outs.Write(this.threshold); 
 
            outs.Write(this.user); 
 
            outs.Write(this.enabled); 
 
        }
 
        public info_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public info_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static oculuslcm.info_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            oculuslcm.info_t o = new oculuslcm.info_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.id = ins.ReadInt16();
 
            this.confidence = ins.ReadSingle();
 
            this.threshold = ins.ReadSingle();
 
            this.user = ins.ReadInt16();
 
            this.enabled = ins.ReadBoolean();
 
        }
 
        public oculuslcm.info_t Copy()
        {
            oculuslcm.info_t outobj = new oculuslcm.info_t();
            outobj.id = this.id;
 
            outobj.confidence = this.confidence;
 
            outobj.threshold = this.threshold;
 
            outobj.user = this.user;
 
            outobj.enabled = this.enabled;
 
            return outobj;
        }
    }
}

