/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace oculuslcm
{
    public sealed class trigger_t : LCM.LCM.LCMEncodable
    {
        public bool trigger;
 
        public trigger_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x4b54427c3c3d322cL;
 
        static trigger_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("oculuslcm.trigger_t"))
                return 0L;
 
            classes.Add("oculuslcm.trigger_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.trigger); 
 
        }
 
        public trigger_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public trigger_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static oculuslcm.trigger_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            oculuslcm.trigger_t o = new oculuslcm.trigger_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.trigger = ins.ReadBoolean();
 
        }
 
        public oculuslcm.trigger_t Copy()
        {
            oculuslcm.trigger_t outobj = new oculuslcm.trigger_t();
            outobj.trigger = this.trigger;
 
            return outobj;
        }
    }
}

