ROS_LEFT    = "left_arm_cmd"
LCM_LEFT    = "left_lcm"
ROS_RIGHT   = "right_arm_cmd"
LCM_RIGHT   = "right_lcm"
ROS_HEAD    = "head_cmd"
LCM_HEAD    = "head_lcm"
ROS_TRIGGER = "trigger_cmd"
LCM_TRIGGER = "trigger_lcm"

ROS_R_VEL   = "right_vel"
LCM_R_VEL   = "right_lcm_vel"
ROS_R_CMD   = "right_cmd"
LCM_R_CMD   = "right_lcm_cmd"

ROS_L_VEL   = "left_vel"
LCM_L_VEL   = "left_lcm_vel"
ROS_L_CMD   = "left_cmd"
LCM_L_CMD   = "left_lcm_cmd"
