"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class oculus_t(object):
    __slots__ = ["position", "orientation", "enabled"]

    def __init__(self):
        self.position = [ 0.0 for dim0 in range(3) ]
        self.orientation = [ 0.0 for dim0 in range(4) ]
        self.enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(oculus_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>4d', *self.orientation[:4]))
        buf.write(struct.pack(">b", self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != oculus_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return oculus_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = oculus_t()
        self.position = struct.unpack('>3d', buf.read(24))
        self.orientation = struct.unpack('>4d', buf.read(32))
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if oculus_t in parents: return 0
        tmphash = (0xea8a3a46f83c6991) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if oculus_t._packed_fingerprint is None:
            oculus_t._packed_fingerprint = struct.pack(">Q", oculus_t._get_hash_recursive([]))
        return oculus_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

