/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace oculuslcm
{
    public sealed class velocity_t : LCM.LCM.LCMEncodable
    {
        public double velocity;
 
        public velocity_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0cd0b79cc8bfd113L;
 
        static velocity_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("oculuslcm.velocity_t"))
                return 0L;
 
            classes.Add("oculuslcm.velocity_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.velocity); 
 
        }
 
        public velocity_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public velocity_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static oculuslcm.velocity_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            oculuslcm.velocity_t o = new oculuslcm.velocity_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.velocity = ins.ReadDouble();
 
        }
 
        public oculuslcm.velocity_t Copy()
        {
            oculuslcm.velocity_t outobj = new oculuslcm.velocity_t();
            outobj.velocity = this.velocity;
 
            return outobj;
        }
    }
}

